// console.log('setTimeout! - 1');
 

// const delayInMilliseconds = 1000; // this is one second

// console.log('setTimeout! - 2');

// const doLater = () => {
//   console.log('setTimeout! - 3');
// };

// console.log('setTimeout! - 4');

// setTimeout(doLater, delayInMilliseconds);

// console.log('setTimeout! - 5');

// als men de bovenstaande code uit commentaar haalt dan krijgt men 
// 1 , 2 , 4, 5, en 3 te zien op het scherm met tussen de meeste cijfers een delay van 1 seconde   


